// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26WMYkV7-mxwab9PeH6TF3PYhgNlj9As',
    appId: '1:1054345411454:web:fa7fe94bc05dddc316d12f',
    messagingSenderId: '1054345411454',
    projectId: 'lechat-8a06c',
    authDomain: 'lechat-8a06c.firebaseapp.com',
    storageBucket: 'lechat-8a06c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_UjrPY2B6dPP0-nKrZOHlASc3iyuE7g',
    appId: '1:1054345411454:android:c1051cbb6b4c35cb16d12f',
    messagingSenderId: '1054345411454',
    projectId: 'lechat-8a06c',
    storageBucket: 'lechat-8a06c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3MwtRSZx_QlQMFNA6WNxxC4Cy593ZqZk',
    appId: '1:1054345411454:ios:97656be67d91466116d12f',
    messagingSenderId: '1054345411454',
    projectId: 'lechat-8a06c',
    storageBucket: 'lechat-8a06c.appspot.com',
    iosClientId: '1054345411454-euuqa997qorn198hataea6masf70j5lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.lechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3MwtRSZx_QlQMFNA6WNxxC4Cy593ZqZk',
    appId: '1:1054345411454:ios:97656be67d91466116d12f',
    messagingSenderId: '1054345411454',
    projectId: 'lechat-8a06c',
    storageBucket: 'lechat-8a06c.appspot.com',
    iosClientId: '1054345411454-euuqa997qorn198hataea6masf70j5lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.lechat',
  );
}
